
import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Classic Denim Jacket",
    price: 1899000,
    description: "A timeless denim jacket made from 100% premium cotton. Perfect for any casual occasion. This jacket features a classic button-front closure, two chest pockets, and adjustable waist tabs for a perfect fit. The durable denim fabric is designed to soften with wear, creating a personalized look over time. It's a versatile layering piece that works well over t-shirts, sweaters, and hoodies.",
    category: "Jackets",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Black"],
    imageUrls: [
      "https://picsum.photos/seed/product1-1/600/800",
      "https://picsum.photos/seed/product1-2/600/800",
      "https://picsum.photos/seed/product1-3/600/800",
      "https://picsum.photos/seed/product1-4/600/800",
    ],
  },
  {
    id: 2,
    name: "Organic Cotton T-Shirt",
    price: 599000,
    description: "Soft, breathable, and eco-friendly. This t-shirt is a wardrobe essential. Made from 100% certified organic cotton, it's gentle on your skin and the environment. It has a classic crew neck and a modern, relaxed fit that's perfect for everyday wear. Available in a range of essential colors, this tee is designed to be a staple in your closet for years to come.",
    category: "T-Shirts",
    sizes: ["S", "M", "L"],
    colors: ["White", "Black", "Gray"],
    imageUrls: [
      "https://picsum.photos/seed/product2-1/600/800",
      "https://picsum.photos/seed/product2-2/600/800",
      "https://picsum.photos/seed/product2-3/600/800",
      "https://picsum.photos/seed/product2-4/600/800",
    ],
  },
  {
    id: 3,
    name: "Slim-Fit Chinos",
    price: 1299000,
    description: "Versatile slim-fit chinos that can be dressed up or down. Made with a comfortable stretch fabric. These chinos are crafted from a high-quality cotton twill with a hint of elastane for added flexibility and comfort. They feature a modern slim fit that's tailored through the leg without being restrictive. Classic four-pocket styling and a zip fly make them a polished choice for any occasion.",
    category: "Pants",
    sizes: ["30", "32", "34", "36"],
    colors: ["Khaki", "Navy", "Gray"],
    imageUrls: [
      "https://picsum.photos/seed/product3-1/600/800",
      "https://picsum.photos/seed/product3-2/600/800",
      "https://picsum.photos/seed/product3-3/600/800",
      "https://picsum.photos/seed/product3-4/600/800",
    ],
  },
  {
    id: 4,
    name: "Wool Blend Sweater",
    price: 2199000,
    description: "Stay warm and stylish with this soft wool blend sweater. Features a classic crew neck design. This sweater is knitted from a premium blend of merino wool and recycled fibers, offering exceptional warmth and a luxuriously soft hand-feel. The timeless crew neck silhouette is complemented by ribbed trim at the collar, cuffs, and hem. It's the perfect piece for layering during colder months.",
    category: "Sweaters",
    sizes: ["M", "L", "XL"],
    colors: ["Charcoal", "Burgundy", "Olive"],
    imageUrls: [
      "https://picsum.photos/seed/product4-1/600/800",
      "https://picsum.photos/seed/product4-2/600/800",
      "https://picsum.photos/seed/product4-3/600/800",
      "https://picsum.photos/seed/product4-4/600/800",
    ],
  },
  {
    id: 5,
    name: "Leather Ankle Boots",
    price: 3499000,
    description: "Handcrafted from genuine leather, these ankle boots offer both style and durability. Featuring a sleek silhouette, a sturdy stacked heel, and an inside zip closure for easy wear. The cushioned insole provides all-day comfort, while the durable rubber outsole ensures reliable traction. These versatile boots pair effortlessly with everything from denim to dresses.",
    category: "Shoes",
    sizes: ["8", "9", "10", "11"],
    colors: ["Brown", "Black"],
    imageUrls: [
      "https://picsum.photos/seed/product5-1/600/800",
      "https://picsum.photos/seed/product5-2/600/800",
      "https://picsum.photos/seed/product5-3/600/800",
      "https://picsum.photos/seed/product5-4/600/800",
    ],
  },
  {
    id: 6,
    name: "Graphic Print Hoodie",
    price: 1499000,
    description: "A comfortable hoodie with a unique graphic print. Made from a soft fleece-lined cotton blend. This pullover hoodie is designed for ultimate comfort, featuring a cozy fleece interior, a drawstring hood, and a roomy kangaroo pocket. The contemporary graphic print on the chest adds a touch of modern style. It's your go-to layer for relaxed weekends and casual outings.",
    category: "Hoodies",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White"],
    imageUrls: [
      "https://picsum.photos/seed/product6-1/600/800",
      "https://picsum.photos/seed/product6-2/600/800",
      "https://picsum.photos/seed/product6-3/600/800",
      "https://picsum.photos/seed/product6-4/600/800",
    ],
  },
  {
    id: 7,
    name: "Linen Button-Up Shirt",
    price: 1199000,
    description: "Lightweight and breathable, this linen shirt is perfect for warm weather. Crafted from a high-quality linen-cotton blend, this shirt offers a naturally cool feel and a relaxed, comfortable fit. It features a classic point collar, a button-front closure, and a single chest pocket. Its effortless style makes it a perfect choice for beach days, vacations, or casual summer evenings.",
    category: "Shirts",
    sizes: ["M", "L", "XL"],
    colors: ["White", "Light Blue", "Beige"],
    imageUrls: [
      "https://picsum.photos/seed/product7-1/600/800",
      "https://picsum.photos/seed/product7-2/600/800",
      "https://picsum.photos/seed/product7-3/600/800",
      "https://picsum.photos/seed/product7-4/600/800",
    ],
  },
  {
    id: 8,
    name: "Performance Shorts",
    price: 999000,
    description: "Moisture-wicking and flexible shorts designed for an active lifestyle. These shorts are engineered with a lightweight, four-way stretch fabric that moves with you. The moisture-wicking technology keeps you dry and comfortable during workouts, while the elastic waistband with an internal drawstring provides a secure fit. Side pockets offer convenient storage for your essentials.",
    category: "Shorts",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Gray", "Navy"],
    imageUrls: [
      "https://picsum.photos/seed/product8-1/600/800",
      "https://picsum.photos/seed/product8-2/600/800",
      "https://picsum.photos/seed/product8-3/600/800",
      "https://picsum.photos/seed/product8-4/600/800",
    ],
  },
    {
    id: 9,
    name: "Water-Resistant Windbreaker",
    price: 1799000,
    description: "Lightweight and stylish, this windbreaker is perfect for unpredictable weather. Folds into its own pocket. Constructed from a durable, water-resistant nylon fabric, this jacket provides protection from wind and light rain. It features a full-zip front, a mesh-lined hood with adjustable drawcords, and elastic cuffs. Best of all, it packs down into its own pocket for easy storage on the go.",
    category: "Jackets",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Navy", "Red", "Yellow"],
    imageUrls: [
      "https://picsum.photos/seed/product9-1/600/800",
      "https://picsum.photos/seed/product9-2/600/800",
      "https://picsum.photos/seed/product9-3/600/800",
      "https://picsum.photos/seed/product9-4/600/800",
    ],
  },
  {
    id: 10,
    name: "Vintage Graphic T-Shirt",
    price: 699000,
    description: "A soft cotton t-shirt with a retro-inspired graphic print. Perfectly worn-in feel. This tee is made from garment-dyed cotton for a vintage look and an ultra-soft feel from the very first wear. The retro graphic is designed to fade and crack over time, enhancing its old-school charm. It has a classic fit that's comfortable and easy to style.",
    category: "T-Shirts",
    sizes: ["S", "M", "L"],
    colors: ["Cream", "Faded Black"],
    imageUrls: [
      "https://picsum.photos/seed/product10-1/600/800",
      "https://picsum.photos/seed/product10-2/600/800",
      "https://picsum.photos/seed/product10-3/600/800",
      "https://picsum.photos/seed/product10-4/600/800",
    ],
  },
  {
    id: 11,
    name: "Cargo Pants",
    price: 1599000,
    description: "Utility-inspired cargo pants with multiple pockets. Made from durable ripstop cotton. These pants blend functionality with modern style. The tough ripstop fabric is built to last, while the relaxed fit and multiple cargo pockets provide comfort and practicality. Adjustable ankle cuffs allow you to customize the silhouette. They are a perfect choice for a rugged, street-style look.",
    category: "Pants",
    sizes: ["30", "32", "34", "36"],
    colors: ["Olive", "Black", "Beige"],
    imageUrls: [
      "https://picsum.photos/seed/product11-1/600/800",
      "https://picsum.photos/seed/product11-2/600/800",
      "https://picsum.photos/seed/product11-3/600/800",
      "https://picsum.photos/seed/product11-4/600/800",
    ],
  },
  {
    id: 12,
    name: "Cashmere Scarf",
    price: 1999000,
    description: "Luxuriously soft 100% cashmere scarf. An elegant accessory for any winter outfit. Experience the unparalleled softness and warmth of pure cashmere. This beautifully crafted scarf is lightweight yet incredibly insulating, making it an essential accessory for cold weather. Finished with classic fringed ends, it adds a touch of sophistication to both casual and formal looks.",
    category: "Accessories",
    sizes: ["One Size"],
    colors: ["Gray", "Camel", "Black"],
    imageUrls: [
      "https://picsum.photos/seed/product12-1/600/800",
      "https://picsum.photos/seed/product12-2/600/800",
      "https://picsum.photos/seed/product12-3/600/800",
      "https://picsum.photos/seed/product12-4/600/800",
    ],
  },
  {
    id: 13,
    name: "Polo Shirt",
    price: 899000,
    description: "A classic polo shirt made from breathable piqué cotton. A smart-casual staple. Our polo shirt is a timeless piece for any wardrobe. The textured piqué cotton fabric is highly breathable and comfortable, perfect for warmer days. It features a traditional ribbed collar and cuffs, a two-button placket, and a regular fit for a classic look.",
    category: "Shirts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Navy", "Green"],
    imageUrls: [
      "https://picsum.photos/seed/product13-1/600/800",
      "https://picsum.photos/seed/product13-2/600/800",
      "https://picsum.photos/seed/product13-3/600/800",
      "https://picsum.photos/seed/product13-4/600/800",
    ],
  },
  {
    id: 14,
    name: "Denim Shorts",
    price: 1099000,
    description: "Classic cut-off denim shorts with a comfortable fit. Perfect for summer days. These shorts are made from sturdy, non-stretch denim that softens with wear. They feature a classic five-pocket design, a zip fly, and a raw, frayed hem for a laid-back, vintage-inspired vibe. The regular fit sits comfortably at the waist, making them your go-to for all summer adventures.",
    category: "Shorts",
    sizes: ["28", "30", "32", "34"],
    colors: ["Light Blue", "Black"],
    imageUrls: [
      "https://picsum.photos/seed/product14-1/600/800",
      "https://picsum.photos/seed/product14-2/600/800",
      "https://picsum.photos/seed/product14-3/600/800",
      "https://picsum.photos/seed/product14-4/600/800",
    ],
  },
  {
    id: 15,
    name: "Leather Belt",
    price: 799000,
    description: "A timeless leather belt with a polished silver buckle. Made from genuine Italian leather. This essential accessory is crafted from high-quality, full-grain Italian leather that will develop a beautiful patina over time. The classic design is complemented by a sleek, polished silver-tone buckle, making it versatile enough to wear with both formal trousers and casual jeans.",
    category: "Accessories",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Brown"],
    imageUrls: [
      "https://picsum.photos/seed/product15-1/600/800",
      "https://picsum.photos/seed/product15-2/600/800",
      "https://picsum.photos/seed/product15-3/600/800",
      "https://picsum.photos/seed/product15-4/600/800",
    ],
  },
  {
    id: 16,
    name: "V-Neck Sweater",
    price: 1899000,
    description: "A versatile V-neck sweater made from fine-gauge merino wool. Lightweight yet warm. This sweater is a perfect layering piece for year-round style. Knitted from extra-fine merino wool, it's exceptionally soft, breathable, and naturally temperature-regulating. The classic V-neck design and regular fit make it easy to wear over a collared shirt for a smart look or a t-shirt for a more casual feel.",
    category: "Sweaters",
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Navy", "Heather Gray"],
    imageUrls: [
      "https://picsum.photos/seed/product16-1/600/800",
      "https://picsum.photos/seed/product16-2/600/800",
      "https://picsum.photos/seed/product16-3/600/800",
      "https://picsum.photos/seed/product16-4/600/800",
    ],
  },
  {
    id: 17,
    name: "Twill Bomber Jacket",
    price: 2499000,
    description: "A modern take on the classic bomber jacket, crafted from durable cotton twill. This jacket updates an iconic silhouette with a clean, contemporary aesthetic. It's made from a sturdy cotton twill fabric and features a full-zip front, ribbed knit collar, cuffs, and hem, and practical side pockets. It's a versatile piece that adds a cool, effortless layer to any outfit.",
    category: "Jackets",
    sizes: ["S", "M", "L"],
    colors: ["Khaki", "Black"],
    imageUrls: [
      "https://picsum.photos/seed/product17-1/600/800",
      "https://picsum.photos/seed/product17-2/600/800",
      "https://picsum.photos/seed/product17-3/600/800",
      "https://picsum.photos/seed/product17-4/600/800",
    ],
  },
  {
    id: 18,
    name: "Canvas Sneakers",
    price: 1399000,
    description: "Low-top canvas sneakers with a durable rubber sole. Comfortable and versatile for everyday wear. These essential sneakers feature a classic lace-up design, a durable canvas upper, and a flexible vulcanized rubber sole for excellent grip and traction. The cushioned footbed ensures all-day comfort. Their timeless design makes them easy to pair with almost any casual outfit.",
    category: "Shoes",
    sizes: ["8", "9", "10", "11", "12"],
    colors: ["White", "Black", "Red"],
    imageUrls: [
      "https://picsum.photos/seed/product18-1/600/800",
      "https://picsum.photos/seed/product18-2/600/800",
      "https://picsum.photos/seed/product18-3/600/800",
      "https://picsum.photos/seed/product18-4/600/800",
    ],
  },
  {
    id: 19,
    name: "Fleece Joggers",
    price: 1199000,
    description: "Ultra-soft fleece joggers perfect for lounging or running errands. Tapered fit for a modern look. Made from a premium cotton-blend fleece, these joggers are incredibly soft and comfortable. They feature a tapered leg for a clean, modern silhouette, an elastic waistband with a drawstring for a custom fit, and ribbed ankle cuffs. Side pockets add practical storage.",
    category: "Pants",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gray", "Black", "Navy"],
    imageUrls: [
      "https://picsum.photos/seed/product19-1/600/800",
      "https://picsum.photos/seed/product19-2/600/800",
      "https://picsum.photos/seed/product19-3/600/800",
      "https://picsum.photos/seed/product19-4/600/800",
    ],
  },
  {
    id: 20,
    name: "Beanie Hat",
    price: 499000,
    description: "A classic ribbed beanie made from a warm wool blend. Essential for cold weather. This beanie is crafted from a soft and insulating blend of wool and recycled fibers. The classic ribbed-knit construction provides a snug and comfortable fit, while the turn-up cuff adds a touch of timeless style. It's the perfect accessory to keep you warm and stylish when the temperature drops.",
    category: "Accessories",
    sizes: ["One Size"],
    colors: ["Black", "Gray", "Orange"],
    imageUrls: [
      "https://picsum.photos/seed/product20-1/600/800",
      "https://picsum.photos/seed/product20-2/600/800",
      "https://picsum.photos/seed/product20-3/600/800",
      "https://picsum.photos/seed/product20-4/600/800",
    ],
  },
];